apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  labels:
    velero.io/csi-volumesnapshot-class: "true"
  name: aws-ebs
driver: ebs.csi.aws.com
deletionPolicy: Retain
