apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helm.yaml
- aws-clusterrole-bind.yaml
- aws-clusterrole.yaml
- aws-ebs-storageclass.yaml
- aws-ebs-snapshotclass.yaml
- github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=v1.0.0

namespace: aws-ebs

patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: ebs-csi-controller
  patch: |-
    - op: add
      path: /spec/template/spec/hostNetwork
      value: true
    - op: add
      path: /spec/template/spec/containers/0/ports/0/containerPort
      value: 19808
    - op: add
      path: /spec/template/spec/containers/3/args/-
      value: "--health-port=19808"
- target:
    version: v1
    kind: DaemonSet
    name: ebs-csi-node
  patch: |-
    - op: replace
      path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchExpressions/0
      value:
        key: "node-role.kubernetes.io/master"
        operator: "DoesNotExist"
